from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = PROJECT_ROOT / "openapi" / "v2.yaml"
GENERATED_TYPES = PROJECT_ROOT / "vue-frontend" / "src" / "api" / "generated" / "v2.ts"


def _document() -> dict[str, Any]:
    value = yaml.safe_load(SPEC_PATH.read_text(encoding="utf-8"))
    assert isinstance(value, dict)
    return value


def _walk(value: Any):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from _walk(child)
    elif isinstance(value, list):
        for child in value:
            yield from _walk(child)


def test_openapi_contract_is_closed_and_all_local_refs_resolve() -> None:
    document = _document()
    assert document["openapi"].startswith("3.1.")
    for node in _walk(document):
        reference = node.get("$ref")
        if not isinstance(reference, str) or not reference.startswith("#/"):
            continue
        resolved: Any = document
        for token in reference[2:].split("/"):
            resolved = resolved[token.replace("~1", "/").replace("~0", "~")]
        assert resolved is not None


def test_required_backend_first_commands_are_explicit() -> None:
    document = _document()
    paths = document["paths"]
    assert {
        "/pages/{page_id}",
        "/pages/{page_id}/document/batch",
        "/pages/{page_id}/repairs",
        "/operations/{operation_id}",
        "/jobs/{job_id}/resume",
        "/jobs/{job_id}/continue",
        "/studio/chat/sessions/{session_id}/messages",
    } <= set(paths)

    schemas = document["components"]["schemas"]
    assert schemas["JobStatus"]["enum"]
    assert schemas["OperationStatus"]["enum"]
    assert set(schemas["StudioMessageCommand"]["required"]) >= {
        "baseSessionRevision",
    }


def test_mutating_commands_use_idempotency_keys() -> None:
    document = _document()
    for path, path_item in document["paths"].items():
        for method in ("post", "put", "patch", "delete"):
            operation = path_item.get(method)
            if operation is None:
                continue
            if operation.get("x-command-mode") == "transient":
                continue
            parameters = [*path_item.get("parameters", []), *operation.get("parameters", [])]
            refs = {parameter.get("$ref") for parameter in parameters}
            assert (
                "#/components/parameters/IdempotencyKey" in refs
            ), f"{method.upper()} {path} has no Idempotency-Key"


def test_typescript_client_is_generated_from_the_contract() -> None:
    generated = GENERATED_TYPES.read_text(encoding="utf-8")
    assert "This file was auto-generated by openapi-typescript." in generated
    assert '"/jobs/{job_id}/resume"' in generated
