import json
import os
import sys
import tempfile
import time
import types
import unittest
import importlib.util
import importlib.machinery
from unittest import mock

from flask import Flask
from flask import Blueprint


PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

def _install_dependency_stubs() -> None:
    if "cv2" not in sys.modules:
        cv2_stub = types.ModuleType("cv2")
        cv2_stub.__spec__ = importlib.machinery.ModuleSpec("cv2", loader=None)
        sys.modules["cv2"] = cv2_stub

    if "openai" not in sys.modules:
        openai_stub = types.ModuleType("openai")

        class _OpenAI:  # pragma: no cover - import stub only
            def __init__(self, *args, **kwargs):
                pass

        openai_stub.OpenAI = _OpenAI
        openai_stub.__spec__ = importlib.machinery.ModuleSpec("openai", loader=None)
        sys.modules["openai"] = openai_stub

    if "torch" not in sys.modules:
        torch_stub = types.ModuleType("torch")
        torch_stub.cuda = types.SimpleNamespace(is_available=lambda: False)
        torch_stub.__spec__ = importlib.machinery.ModuleSpec("torch", loader=None)
        sys.modules["torch"] = torch_stub


def tearDownModule():
    for module_name in ("cv2", "openai", "torch"):
        sys.modules.pop(module_name, None)


def _write_plugin(plugin_dir: str, plugin_id: str, class_name: str = "ExistingPlugin") -> None:
    os.makedirs(plugin_dir, exist_ok=True)
    with open(os.path.join(plugin_dir, "__init__.py"), "w", encoding="utf-8") as file:
        file.write(f"from .plugin import {class_name}\n")
    with open(os.path.join(plugin_dir, "plugin.py"), "w", encoding="utf-8") as file:
        file.write(
            "from src.plugins.base import PluginBase\n\n"
            f"class {class_name}(PluginBase):\n"
            f"    plugin_id = {plugin_id!r}\n"
            f"    display_name = {plugin_id!r}\n"
            "    plugin_version = '1.0.0'\n"
            "    plugin_author = 'Tests'\n"
            "    plugin_description = 'test plugin'\n"
            "    default_enabled = False\n"
            "    supported_steps = ('ocr',)\n"
            "    supported_modes = ('standard',)\n"
            "    def after_ocr(self, context, result):\n"
            "        return result\n"
        )


class FakePluginAgentController:
    def plan_turn(self, session, skill_markdown, agent_config):
        if not skill_markdown:
            raise AssertionError("skill markdown should be injected")
        if session.mode == "create" and session.pending_target is None and session.locked_target is None:
            return {
                "assistant_message": "我建议创建一个新插件。",
                "target_proposal": {
                    "plugin_id": "auto_plugin",
                    "display_name": "Auto Plugin",
                    "supported_steps": ["ocr"],
                    "supported_modes": ["standard"],
                },
            }
        return {
            "assistant_message": "已记录需求。",
        }

    def execute(self, session, skill_markdown, agent_config, tool_executor, emit_event):
        if not skill_markdown:
            raise AssertionError("skill markdown should be injected")
        emit_event("log", {"message": "开始执行"})
        if session.locked_target is None:
            raise RuntimeError("locked target missing")
        plugin_id = session.locked_target.plugin_id
        class_name = "".join(part.capitalize() for part in plugin_id.split("_")) or "GeneratedPlugin"
        tool_executor.write_file("__init__.py", f"from .plugin import {class_name}\n")
        tool_executor.write_file(
            "plugin.py",
            "from src.plugins.base import PluginBase\n\n"
            f"class {class_name}(PluginBase):\n"
            f"    plugin_id = {plugin_id!r}\n"
            f"    display_name = {session.locked_target.display_name!r}\n"
            "    plugin_version = '1.0.0'\n"
            "    plugin_author = 'Agent'\n"
            "    plugin_description = 'generated by tests'\n"
            "    default_enabled = False\n"
            "    supported_steps = ('ocr',)\n"
            "    supported_modes = ('standard',)\n"
            "    def after_ocr(self, context, result):\n"
            "        return result\n",
        )
        validation = tool_executor.validate_plugin()
        emit_event("validation", validation)
        return {
            "assistant_message": "插件已生成完成。",
            "refresh_plugins": True,
            "validation": validation,
        }


class SlowCancelAwareController:
    def plan_turn(self, session, skill_markdown, agent_config):
        return {"assistant_message": "已记录需求。"}

    def execute(self, session, skill_markdown, agent_config, tool_executor, emit_event):
        deadline = time.time() + 2.0
        while time.time() < deadline:
            if tool_executor.is_cancelled():
                raise RuntimeError("任务已取消")
            time.sleep(0.05)
        return {
            "assistant_message": "不应执行到这里",
            "refresh_plugins": False,
            "validation": {"success": True},
        }


class PluginAgentRuntimeTests(unittest.TestCase):
    def setUp(self) -> None:
        _install_dependency_stubs()
        from src.core.plugin_agent.runtime import PluginAgentRuntime
        from src.core.plugin_agent.models import PluginAgentMessage
        from src.core.plugin_agent.tools import LockedPluginTarget, PluginAgentToolExecutor

        self.PluginAgentRuntime = PluginAgentRuntime
        self.PluginAgentMessage = PluginAgentMessage
        self.LockedPluginTarget = LockedPluginTarget
        self.PluginAgentToolExecutor = PluginAgentToolExecutor

    def test_tool_executor_rejects_path_escape_outside_locked_plugin(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            target_dir = os.path.join(plugins_root, "safe_plugin")
            _write_plugin(target_dir, "safe_plugin", class_name="SafePlugin")

            target = self.LockedPluginTarget(
                mode="modify",
                plugin_id="safe_plugin",
                display_name="Safe Plugin",
                plugin_dir=target_dir,
            )
            executor = self.PluginAgentToolExecutor(target=target, skill_markdown="skill")

            with self.assertRaisesRegex(ValueError, "插件目录"):
                executor.read_file("../other_plugin/plugin.py")

            with self.assertRaisesRegex(ValueError, "插件目录"):
                executor.write_file("..\\outside.py", "print('bad')")

    def test_validate_plugin_runs_in_isolated_mode(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            target_dir = os.path.join(plugins_root, "validate_me")
            _write_plugin(target_dir, "validate_me", class_name="ValidateMePlugin")

            target = self.LockedPluginTarget(
                mode="modify",
                plugin_id="validate_me",
                display_name="Validate Me",
                plugin_dir=target_dir,
            )
            executor = self.PluginAgentToolExecutor(target=target, skill_markdown="skill")

            result = executor.validate_plugin()

            self.assertTrue(result["success"])
            self.assertEqual(result["plugin"]["id"], "validate_me")
            self.assertEqual(result["plugin"]["display_name"], "validate_me")

    def test_create_flow_requires_target_lock_before_execution(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            refresh_calls = []
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda target: refresh_calls.append(target.plugin_id),
                skill_markdown="skill",
            )

            session = runtime.create_session("create")
            runtime.send_user_message(session.session_id, "做一个OCR后清洗插件", {})
            self.assertEqual(runtime.get_session(session.session_id).run_state, "awaiting_target_lock")

            with self.assertRaisesRegex(ValueError, "锁定"):
                runtime.start_execution(session.session_id, {})

            runtime.lock_target(
                session.session_id,
                {
                    "plugin_id": "auto_plugin",
                    "display_name": "Auto Plugin",
                    "supported_steps": ["ocr"],
                    "supported_modes": ["standard"],
                },
            )
            runtime.start_execution(session.session_id, {})

            deadline = time.time() + 3.0
            while time.time() < deadline:
                updated = runtime.get_session(session.session_id)
                if updated and updated.run_state in {"completed", "failed"}:
                    break
                time.sleep(0.05)

            updated = runtime.get_session(session.session_id)
            self.assertIsNotNone(updated)
            self.assertEqual(updated.run_state, "completed")
            self.assertEqual(updated.locked_target.plugin_id, "auto_plugin")
            self.assertIn("auto_plugin", refresh_calls)
            self.assertTrue(os.path.exists(os.path.join(plugins_root, "auto_plugin", "plugin.py")))
            self.assertTrue(any(event.type == "log" for event in updated.events))
            self.assertTrue(any(event.type == "done" for event in updated.events))

    def test_delete_session_cancels_running_execution_without_leaking_active_session(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            plugin_dir = os.path.join(plugins_root, "existing_plugin")
            _write_plugin(plugin_dir, "existing_plugin", class_name="ExistingPlugin")

            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=SlowCancelAwareController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )
            session = runtime.create_session_with_display_name(
                "modify",
                plugin_id="existing_plugin",
                display_name="Existing Plugin",
            )
            session.messages.append(
                self.PluginAgentMessage(
                    id="user_1",
                    role="user",
                    content="修改这个插件",
                )
            )
            runtime.start_execution(session.session_id, {})

            deleted = runtime.delete_session(session.session_id)
            self.assertTrue(deleted)
            cancelled_session = runtime.get_session(session.session_id)
            self.assertIsNotNone(cancelled_session)
            self.assertEqual(cancelled_session.run_state, "cancelled")
            with self.assertRaisesRegex(ValueError, "已有活跃会话"):
                runtime.create_session("create")

            deadline = time.time() + 3.0
            while time.time() < deadline:
                thread = runtime._running_threads.get(session.session_id)
                if thread is None or not thread.is_alive():
                    break
                time.sleep(0.05)

            self.assertNotIn(session.session_id, runtime._running_threads)
            self.assertNotIn(session.session_id, runtime._cancel_flags)
            self.assertIsNone(runtime.get_session(session.session_id))


class PluginAgentApiTests(unittest.TestCase):
    def setUp(self) -> None:
        _install_dependency_stubs()
        from src.core.plugin_agent.runtime import PluginAgentRuntime

        self.PluginAgentRuntime = PluginAgentRuntime
        system_dir = os.path.join(PROJECT_ROOT, "src", "app", "api", "system")
        package_name = "isolated_plugin_agent_system"
        package_module = types.ModuleType(package_name)
        package_module.__path__ = [system_dir]
        package_module.system_bp = Blueprint("isolated_system_api", __name__, url_prefix="/api")
        sys.modules[package_name] = package_module

        module_path = os.path.join(system_dir, "plugin_agent.py")
        spec = importlib.util.spec_from_file_location(f"{package_name}.plugin_agent", module_path)
        module = importlib.util.module_from_spec(spec)
        assert spec is not None and spec.loader is not None
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        self.plugin_agent_module = module

        self.app = Flask(__name__)
        self.app.register_blueprint(package_module.system_bp)
        self.client = self.app.test_client()

    def test_settings_endpoint_returns_examples(self) -> None:
        response = self.client.get("/api/plugins/agent/settings")

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertTrue(payload["success"])
        self.assertIn("prompt_examples", payload)
        self.assertGreaterEqual(len(payload["prompt_examples"]), 3)
        self.assertIsNone(payload["session"])

    def test_modify_session_requires_existing_plugin(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )

            with mock.patch.object(self.plugin_agent_module, "get_plugin_agent_runtime", return_value=runtime):
                response = self.client.post(
                    "/api/plugins/agent/sessions",
                    json={"mode": "modify", "plugin_id": "missing_plugin"},
                )

        self.assertEqual(response.status_code, 400)
        self.assertIn("插件不存在", response.get_json()["error"])

    def test_modify_session_locks_selected_plugin_immediately(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            _write_plugin(os.path.join(plugins_root, "existing_plugin"), "existing_plugin")
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )

            with mock.patch.object(self.plugin_agent_module, "get_plugin_agent_runtime", return_value=runtime):
                response = self.client.post(
                    "/api/plugins/agent/sessions",
                    json={"mode": "modify", "plugin_id": "existing_plugin"},
                )

        self.assertEqual(response.status_code, 200)
        payload = response.get_json()
        self.assertTrue(payload["success"])
        self.assertEqual(payload["session"]["locked_target"]["plugin_id"], "existing_plugin")

    def test_create_session_start_is_blocked_before_lock_target(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )

            with mock.patch.object(self.plugin_agent_module, "get_plugin_agent_runtime", return_value=runtime):
                create_response = self.client.post("/api/plugins/agent/sessions", json={"mode": "create"})
                session_id = create_response.get_json()["session"]["session_id"]

                send_response = self.client.post(
                    f"/api/plugins/agent/sessions/{session_id}/messages",
                    json={"content": "请做一个OCR插件", "agent_config": {}},
                )
                self.assertEqual(send_response.status_code, 200)

                start_response = self.client.post(
                    f"/api/plugins/agent/sessions/{session_id}/start",
                    json={"agent_config": {}},
                )

        self.assertEqual(start_response.status_code, 409)
        self.assertIn("锁定", start_response.get_json()["error"])

    def test_event_stream_contains_assistant_event_after_plan_turn(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            plugins_root = os.path.join(temp_dir, "plugins")
            runtime = self.PluginAgentRuntime(
                plugins_root=plugins_root,
                controller=FakePluginAgentController(),
                finalize_refresh=lambda _target: None,
                skill_markdown="skill",
            )

            with mock.patch.object(self.plugin_agent_module, "get_plugin_agent_runtime", return_value=runtime):
                create_response = self.client.post("/api/plugins/agent/sessions", json={"mode": "create"})
                session_id = create_response.get_json()["session"]["session_id"]

                self.client.post(
                    f"/api/plugins/agent/sessions/{session_id}/messages",
                    json={"content": "请做一个OCR插件", "agent_config": {}},
                )
                stream_response = self.client.get(f"/api/plugins/agent/sessions/{session_id}/events?after_id=0")

        self.assertEqual(stream_response.status_code, 200)
        body = b"".join(stream_response.response).decode("utf-8")
        self.assertIn("event: assistant", body)
        self.assertIn("event: state", body)


if __name__ == "__main__":
    unittest.main()
