"""backend v2 foundation

Revision ID: 0001
Revises:
Create Date: 2026-07-28 22:42:20.185120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_app_settings_revision_positive')),
    sa.PrimaryKeyConstraint('domain', name=op.f('pk_app_settings'))
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('integrity_status', sa.String(length=16), server_default='ok', nullable=False),
    sa.Column('gc_marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("integrity_status IN ('ok', 'missing')", name=op.f('ck_assets_integrity_status_values')),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_assets_byte_size_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('relative_path', name=op.f('uq_assets_relative_path'))
    )
    op.create_index('ix_assets_checksum', 'assets', ['checksum'], unique=False)
    op.create_index('ix_assets_gc_marked_at', 'assets', ['gc_marked_at'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials')),
    sa.UniqueConstraint('domain', 'provider', name=op.f('uq_credentials_domain'))
    )
    op.create_table('idempotency_records',
    sa.Column('scope', sa.String(length=500), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('http_status >= 200 AND http_status < 300', name=op.f('ck_idempotency_records_successful_status')),
    sa.PrimaryKeyConstraint('scope', 'key', name=op.f('pk_idempotency_records'))
    )
    op.create_index('ix_idempotency_records_expires_at', 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('job_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('status_summary_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_batches'))
    )
    op.create_table('object_commit_journal',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('staging_relative_path', sa.Text(), nullable=False),
    sa.Column('final_relative_path', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("state IN ('staged','file_published','database_committed')", name=op.f('ck_object_commit_journal_state_values')),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_object_commit_journal'))
    )
    op.create_table('plugins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='enabled', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("state IN ('enabled', 'disabled', 'error')", name=op.f('ck_plugins_state_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugins'))
    )
    op.create_table('process_epochs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recovery_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('launcher','api','worker')", name=op.f('ck_process_epochs_role_values')),
    sa.CheckConstraint("status IN ('active','lost','closed')", name=op.f('ck_process_epochs_status_values')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_epochs'))
    )
    op.create_index('ix_process_epochs_role_status', 'process_epochs', ['role', 'status'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_factory_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('translate', 'textbox', 'ai_vision_ocr', 'hq_translate', 'proofreading', 'batch_analysis', 'segment_summary', 'chapter_summary', 'book_overview', 'group_summary', 'qa_response', 'question_decompose', 'analysis_system')", name=op.f('ck_prompts_type_values')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_prompts_revision_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts')),
    sa.UniqueConstraint('type', 'name', name=op.f('uq_prompts_type'))
    )
    op.create_table('queue_state',
    sa.Column('singleton_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('queue_revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('queue_revision >= 1', name=op.f('ck_queue_state_revision_positive')),
    sa.CheckConstraint('singleton_id = 1', name=op.f('ck_queue_state_single_row')),
    sa.PrimaryKeyConstraint('singleton_id', name=op.f('pk_queue_state'))
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('api_executor_leases',
    sa.Column('api_epoch_id', sa.String(length=36), nullable=False),
    sa.Column('lease_token', sa.String(length=200), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_epoch_id'], ['process_epochs.id'], name=op.f('fk_api_executor_leases_api_epoch_id_process_epochs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_epoch_id', name=op.f('pk_api_executor_leases'))
    )
    op.create_table('books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), server_default='library', nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('chapter_order_revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('cover_asset_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('library', 'quick_workspace')", name=op.f('ck_books_kind_values')),
    sa.CheckConstraint('chapter_order_revision >= 1', name=op.f('ck_books_chapter_order_revision_positive')),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['assets.id'], name=op.f('fk_books_cover_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.create_index('uq_books_one_quick_workspace', 'books', ['kind'], unique=True, sqlite_where=sa.text("kind = 'quick_workspace'"))
    op.create_table('credential_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('secret_json', sa.Text(), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_credential_versions_version_positive')),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name=op.f('fk_credential_versions_credential_id_credentials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_versions')),
    sa.UniqueConstraint('credential_id', 'version', name=op.f('uq_credential_versions_credential_id'))
    )
    op.create_table('fonts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('builtin_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(kind = 'builtin' AND builtin_key IS NOT NULL AND asset_id IS NULL) OR (kind = 'uploaded' AND builtin_key IS NULL AND asset_id IS NOT NULL)", name=op.f('ck_fonts_source_shape')),
    sa.CheckConstraint("kind IN ('builtin', 'uploaded')", name=op.f('ck_fonts_kind_values')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_fonts_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fonts'))
    )
    op.create_index('uq_fonts_builtin_key', 'fonts', ['builtin_key'], unique=True, sqlite_where=sa.text('builtin_key IS NOT NULL'))
    op.create_table('plugin_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('package_relative_path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('manifest_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], name=op.f('fk_plugin_versions_plugin_id_plugins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_versions')),
    sa.UniqueConstraint('package_relative_path', name=op.f('uq_plugin_versions_package_relative_path')),
    sa.UniqueConstraint('plugin_id', 'version', name=op.f('uq_plugin_versions_plugin_id'))
    )
    op.create_table('transient_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('connection_token_hash', sa.String(length=64), nullable=False),
    sa.Column('connection_open', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('worker_epoch_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('lease_token', sa.String(length=200), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('vector_query')", name=op.f('ck_transient_requests_kind_values')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name=op.f('ck_transient_requests_status_values')),
    sa.ForeignKeyConstraint(['worker_epoch_id'], ['process_epochs.id'], name=op.f('fk_transient_requests_worker_epoch_id_process_epochs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transient_requests'))
    )
    op.create_table('worker_leases',
    sa.Column('worker_epoch_id', sa.String(length=36), nullable=False),
    sa.Column('lease_token', sa.String(length=200), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_epoch_id'], ['process_epochs.id'], name=op.f('fk_worker_leases_worker_epoch_id_process_epochs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_epoch_id', name=op.f('pk_worker_leases'))
    )
    op.create_table('book_settings',
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_settings_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'domain', name=op.f('pk_book_settings'))
    )
    op.create_table('book_tags',
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_tags_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_book_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'tag_id', name=op.f('pk_book_tags'))
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('page_order_revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('write_intent_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('settings_memory_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('settings_memory_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('settings_memory_revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_chapters_ordinal_positive')),
    sa.CheckConstraint('page_order_revision >= 1', name=op.f('ck_chapters_page_order_revision_positive')),
    sa.CheckConstraint('write_intent_generation >= 0', name=op.f('ck_chapters_intent_generation_nonnegative')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_chapters_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters')),
    sa.UniqueConstraint('book_id', 'ordinal', name=op.f('uq_chapters_book_id'))
    )
    op.create_table('credential_current_versions',
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('credential_version_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_credential_current_versions_revision_positive')),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name=op.f('fk_credential_current_versions_credential_id_credentials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_version_id'], ['credential_versions.id'], name=op.f('fk_credential_current_versions_credential_version_id_credential_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('credential_id', name=op.f('pk_credential_current_versions')),
    sa.UniqueConstraint('credential_version_id', name=op.f('uq_credential_current_versions_credential_version_id'))
    )
    op.create_table('plugin_current_versions',
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('plugin_version_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_plugin_current_versions_revision_positive')),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], name=op.f('fk_plugin_current_versions_plugin_id_plugins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plugin_version_id'], ['plugin_versions.id'], name=op.f('fk_plugin_current_versions_plugin_version_id_plugin_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('plugin_id', name=op.f('pk_plugin_current_versions')),
    sa.UniqueConstraint('plugin_version_id', name=op.f('uq_plugin_current_versions_plugin_version_id'))
    )
    op.create_table('provider_rate_limits',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('credential_version_id', sa.String(length=36), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('request_count >= 0', name=op.f('ck_provider_rate_limits_request_count_nonnegative')),
    sa.CheckConstraint('rpm_limit >= 1', name=op.f('ck_provider_rate_limits_rpm_limit_positive')),
    sa.ForeignKeyConstraint(['credential_version_id'], ['credential_versions.id'], name=op.f('fk_provider_rate_limits_credential_version_id_credential_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('provider', 'credential_version_id', name=op.f('pk_provider_rate_limits'))
    )
    op.create_table('provider_settings',
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('credential_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['credential_version_id'], ['credential_versions.id'], name=op.f('fk_provider_settings_credential_version_id_credential_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('domain', 'provider', name=op.f('pk_provider_settings'))
    )
    op.create_table('studio_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('generation', sa.Integer(), server_default='1', nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('generation >= 1', name=op.f('ck_studio_documents_generation_positive')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_studio_documents_revision_positive')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_studio_documents_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studio_documents'))
    )
    op.create_table('translation_constraints',
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_translation_constraints_revision_positive')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_translation_constraints_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', name=op.f('pk_translation_constraints'))
    )
    op.create_table('import_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('owner_token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_import_leases_chapter_id_chapters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_leases')),
    sa.UniqueConstraint('chapter_id', name=op.f('uq_import_leases_chapter_id'))
    )
    op.create_index('ix_import_leases_expires_at', 'import_leases', ['expires_at'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('logical_source_path', sa.Text(), nullable=False),
    sa.Column('source_revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('document_revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rendered_revision', sa.Integer(), nullable=True),
    sa.Column('render_status', sa.String(length=32), server_default='not_rendered', nullable=False),
    sa.Column('detection_state', sa.String(length=32), server_default='unprocessed', nullable=False),
    sa.Column('default_font_id', sa.String(length=36), nullable=True),
    sa.Column('page_style_defaults_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('page_style_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('warnings_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("render_status IN ('not_rendered','ready','stale','rendering','render_failed','awaiting_repair','repair_failed')", name=op.f('ck_pages_render_status_values')),
    sa.CheckConstraint('document_revision >= 1', name=op.f('ck_pages_document_revision_positive')),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_pages_ordinal_positive')),
    sa.CheckConstraint('source_revision >= 1', name=op.f('ck_pages_source_revision_positive')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_pages_chapter_id_chapters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_font_id'], ['fonts.id'], name=op.f('fk_pages_default_font_id_fonts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pages')),
    sa.UniqueConstraint('chapter_id', 'logical_source_path', name=op.f('uq_pages_chapter_id')),
    sa.UniqueConstraint('chapter_id', 'ordinal', name=op.f('uq_pages_chapter_id'))
    )
    op.create_table('studio_chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('generation', sa.Integer(), server_default='1', nullable=False),
    sa.Column('runtime_state_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('runtime_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['studio_documents.id'], name=op.f('fk_studio_chat_sessions_document_id_studio_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studio_chat_sessions'))
    )
    op.create_table('web_import_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('config_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('temp_relative_path', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('extracting','ready','committing','completed','failed','cancelled')", name=op.f('ck_web_import_drafts_status_values')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_web_import_drafts_book_id_books'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_web_import_drafts_chapter_id_chapters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_import_drafts'))
    )
    op.create_table('bubbles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('font_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_bubbles_ordinal_positive')),
    sa.CheckConstraint('updated_revision >= 1', name=op.f('ck_bubbles_updated_revision_positive')),
    sa.ForeignKeyConstraint(['font_id'], ['fonts.id'], name=op.f('fk_bubbles_font_id_fonts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_bubbles_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bubbles')),
    sa.UniqueConstraint('page_id', 'ordinal', name=op.f('uq_bubbles_page_id'))
    )
    op.create_table('chapter_navigation_state',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('last_visited_page_id', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_chapter_navigation_state_revision_positive')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_chapter_navigation_state_chapter_id_chapters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_visited_page_id'], ['pages.id'], name=op.f('fk_chapter_navigation_state_last_visited_page_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chapter_id', name=op.f('pk_chapter_navigation_state'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('queue_rank', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('web_import_draft_id', sa.String(length=36), nullable=True),
    sa.Column('blocked_reason', sa.String(length=64), nullable=True),
    sa.Column('blocked_by_job_id', sa.String(length=36), nullable=True),
    sa.Column('blocked_by_import_lease_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('lease_token', sa.String(length=200), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_epoch_id', sa.String(length=36), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('config_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('latest_progress_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('target_display_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("blocked_reason IS NULL OR blocked_reason IN ('blocked_by_job','blocked_by_import_lease','draining_immediate_writes')", name=op.f('ck_jobs_blocked_reason_values')),
    sa.CheckConstraint("kind IN ('translation', 'remove_text', 'detect', 'style_apply', 'text_import', 'container_import', 'web_extract', 'web_import_commit', 'export', 'insight_analysis', 'insight_export', 'vector_rebuild', 'continuation', 'derived_rebuild', 'plugin_agent')", name=op.f('ck_jobs_kind_values')),
    sa.CheckConstraint("status IN ('queued', 'running', 'pausing', 'paused', 'cancelling', 'cancelled', 'completed', 'completed_with_errors', 'failed', 'interrupted')", name=op.f('ck_jobs_status_values')),
    sa.CheckConstraint('(blocked_by_job_id IS NULL OR blocked_by_import_lease_id IS NULL)', name=op.f('ck_jobs_single_blocker')),
    sa.CheckConstraint('queue_rank IS NULL OR queue_rank >= 1', name=op.f('ck_jobs_queue_rank_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['job_batches.id'], name=op.f('fk_jobs_batch_id_job_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['blocked_by_import_lease_id'], ['import_leases.id'], name=op.f('fk_jobs_blocked_by_import_lease_id_import_leases'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['blocked_by_job_id'], ['jobs.id'], name=op.f('fk_jobs_blocked_by_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_jobs_book_id_books'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_jobs_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_jobs_page_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['web_import_draft_id'], ['web_import_drafts.id'], name=op.f('fk_jobs_web_import_draft_id_web_import_drafts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_epoch_id'], ['process_epochs.id'], name=op.f('fk_jobs_worker_epoch_id_process_epochs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('queue_rank', name=op.f('uq_jobs_queue_rank'))
    )
    op.create_index('ix_jobs_queue_claim', 'jobs', ['status', 'queue_rank'], unique=False)
    op.execute(
        "CREATE UNIQUE INDEX uq_jobs_one_current ON jobs ((1)) "
        "WHERE status IN ('running','pausing','paused','cancelling')"
    )
    op.create_index('uq_jobs_one_nonterminal_translation_per_chapter', 'jobs', ['chapter_id'], unique=True, sqlite_where=sa.text("kind = 'translation' AND status IN ('queued', 'running', 'pausing', 'paused', 'cancelling', 'interrupted') AND chapter_id IS NOT NULL"))
    op.create_table('render_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('requested_revision', sa.Integer(), nullable=False),
    sa.Column('rendering_revision', sa.Integer(), nullable=True),
    sa.Column('completed_revision', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('executor_epoch_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('lease_token', sa.String(length=200), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name=op.f('ck_render_requests_status_values')),
    sa.CheckConstraint('requested_revision >= 1', name=op.f('ck_render_requests_requested_revision_positive')),
    sa.ForeignKeyConstraint(['executor_epoch_id'], ['process_epochs.id'], name=op.f('fk_render_requests_executor_epoch_id_process_epochs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_render_requests_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_render_requests')),
    sa.UniqueConstraint('page_id', name=op.f('uq_render_requests_page_id'))
    )
    op.create_index('ix_render_requests_claim', 'render_requests', ['status', 'updated_at'], unique=False)
    op.create_table('studio_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('system','user','assistant')", name=op.f('ck_studio_messages_role_values')),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_studio_messages_ordinal_positive')),
    sa.ForeignKeyConstraint(['session_id'], ['studio_chat_sessions.id'], name=op.f('fk_studio_messages_session_id_studio_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_studio_messages')),
    sa.UniqueConstraint('session_id', 'ordinal', name=op.f('uq_studio_messages_session_id'))
    )
    op.create_table('web_import_draft_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('temp_relative_path', sa.Text(), nullable=False),
    sa.Column('thumbnail_asset_id', sa.String(length=36), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['web_import_drafts.id'], name=op.f('fk_web_import_draft_pages_draft_id_web_import_drafts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thumbnail_asset_id'], ['assets.id'], name=op.f('fk_web_import_draft_pages_thumbnail_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_import_draft_pages')),
    sa.UniqueConstraint('draft_id', 'ordinal', name=op.f('uq_web_import_draft_pages_draft_id'))
    )
    op.create_table('chapter_write_intents',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('intent_set_id', sa.String(length=36), nullable=False),
    sa.Column('intent_generation', sa.Integer(), nullable=False),
    sa.Column('worker_epoch_id', sa.String(length=36), nullable=False),
    sa.Column('lease_token', sa.String(length=200), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('intent_generation >= 1', name=op.f('ck_chapter_write_intents_generation_positive')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_chapter_write_intents_chapter_id_chapters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_chapter_write_intents_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_epoch_id'], ['process_epochs.id'], name=op.f('fk_chapter_write_intents_worker_epoch_id_process_epochs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id', name=op.f('pk_chapter_write_intents'))
    )
    op.create_index('ix_chapter_write_intents_epoch_expiry', 'chapter_write_intents', ['worker_epoch_id', 'lease_expires_at'], unique=False)
    op.create_index('ix_chapter_write_intents_job_set', 'chapter_write_intents', ['job_id', 'intent_set_id'], unique=False)
    op.create_table('chapter_write_locks',
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('lock_generation', sa.Integer(), nullable=False),
    sa.Column('owner_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('lease_token', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('lock_generation >= 1', name=op.f('ck_chapter_write_locks_generation_positive')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_chapter_write_locks_chapter_id_chapters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_chapter_write_locks_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_id', name=op.f('pk_chapter_write_locks'))
    )
    op.create_index('ix_chapter_write_locks_job', 'chapter_write_locks', ['job_id'], unique=False)
    op.create_table('job_artifacts',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_job_artifacts_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_artifacts_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'kind', name=op.f('pk_job_artifacts'))
    )
    op.create_table('job_config_snapshots',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_config_snapshots_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_job_config_snapshots'))
    )
    op.create_table('job_credential_snapshots',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('credential_version_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['credential_version_id'], ['credential_versions.id'], name=op.f('fk_job_credential_snapshots_credential_version_id_credential_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_credential_snapshots_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'credential_version_id', 'role', name=op.f('pk_job_credential_snapshots'))
    )
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('payload_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_index('ix_job_events_job_cursor', 'job_events', ['job_id', 'id'], unique=False)
    op.create_table('job_font_snapshots',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('font_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['font_id'], ['fonts.id'], name=op.f('fk_job_font_snapshots_font_id_fonts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_font_snapshots_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'font_id', 'role', name=op.f('pk_job_font_snapshots'))
    )
    op.create_table('job_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','skipped','cancelled')", name=op.f('ck_job_items_status_values')),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_job_items_ordinal_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_items_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_job_items_page_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_items')),
    sa.UniqueConstraint('job_id', 'ordinal', name=op.f('uq_job_items_job_id'))
    )
    op.create_table('job_plugin_snapshots',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('plugin_version_id', sa.String(length=36), nullable=False),
    sa.Column('config_json', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_plugin_snapshots_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plugin_version_id'], ['plugin_versions.id'], name=op.f('fk_job_plugin_snapshots_plugin_version_id_plugin_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id', 'plugin_version_id', name=op.f('pk_job_plugin_snapshots'))
    )
    op.create_table('operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('executor_role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('bubble_id', sa.String(length=36), nullable=True),
    sa.Column('studio_document_id', sa.String(length=36), nullable=True),
    sa.Column('studio_session_id', sa.String(length=36), nullable=True),
    sa.Column('base_revision', sa.Integer(), nullable=True),
    sa.Column('base_generation', sa.Integer(), nullable=True),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('request_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('executor_epoch_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('lease_token', sa.String(length=200), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(kind IN ('bubble_ocr','bubble_color','bubble_translate') AND page_id IS NOT NULL AND bubble_id IS NOT NULL AND studio_document_id IS NULL AND studio_session_id IS NULL) OR (kind IN ('page_detect','page_repair') AND page_id IS NOT NULL AND studio_document_id IS NULL AND studio_session_id IS NULL) OR (kind = 'studio_generate' AND studio_document_id IS NOT NULL AND page_id IS NULL AND bubble_id IS NULL AND studio_session_id IS NULL) OR (kind IN ('studio_chat','studio_summary') AND studio_session_id IS NOT NULL AND page_id IS NULL AND bubble_id IS NULL AND studio_document_id IS NULL)", name=op.f('ck_operations_kind_target_shape')),
    sa.CheckConstraint("(kind IN ('bubble_ocr','bubble_color','page_detect') AND executor_role = 'worker') OR (kind IN ('bubble_translate','studio_generate','studio_chat','studio_summary') AND executor_role = 'api') OR (kind = 'page_repair')", name=op.f('ck_operations_kind_executor_shape')),
    sa.CheckConstraint("executor_role IN ('api','worker')", name=op.f('ck_operations_executor_role_values')),
    sa.CheckConstraint("kind IN ('bubble_ocr', 'bubble_color', 'page_detect', 'page_repair', 'bubble_translate', 'studio_generate', 'studio_chat', 'studio_summary')", name=op.f('ck_operations_kind_values')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name=op.f('ck_operations_status_values')),
    sa.ForeignKeyConstraint(['bubble_id'], ['bubbles.id'], name=op.f('fk_operations_bubble_id_bubbles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executor_epoch_id'], ['process_epochs.id'], name=op.f('fk_operations_executor_epoch_id_process_epochs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_operations_page_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_document_id'], ['studio_documents.id'], name=op.f('fk_operations_studio_document_id_studio_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['studio_session_id'], ['studio_chat_sessions.id'], name=op.f('fk_operations_studio_session_id_studio_chat_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations'))
    )
    op.create_index('ix_operations_executor_claim', 'operations', ['executor_role', 'status', 'created_at'], unique=False)
    op.create_index('uq_operations_one_active_page_write', 'operations', ['page_id'], unique=True, sqlite_where=sa.text("page_id IS NOT NULL AND status IN ('pending', 'running') AND kind IN ('bubble_ocr', 'bubble_color', 'page_detect', 'page_repair', 'bubble_translate')"))
    op.create_index('uq_operations_one_active_studio_generate', 'operations', ['studio_document_id'], unique=True, sqlite_where=sa.text("studio_document_id IS NOT NULL AND status IN ('pending', 'running') AND kind = 'studio_generate'"))
    op.create_index('uq_operations_one_active_studio_session', 'operations', ['studio_session_id'], unique=True, sqlite_where=sa.text("studio_session_id IS NOT NULL AND status IN ('pending', 'running') AND kind IN ('studio_chat', 'studio_summary')"))
    op.create_table('job_asset_inputs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('binding_phase', sa.String(length=16), nullable=False),
    sa.Column('job_item_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint("binding_phase IN ('create','item_start','checkpoint')", name=op.f('ck_job_asset_inputs_binding_phase_values')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_job_asset_inputs_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_asset_inputs_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_item_id'], ['job_items.id'], name=op.f('fk_job_asset_inputs_job_item_id_job_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'asset_id', 'role', name=op.f('pk_job_asset_inputs'))
    )
    op.create_table('job_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_item_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('checkpoint_json', sa.Text(), nullable=True),
    sa.Column('checkpoint_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','skipped','cancelled')", name=op.f('ck_job_steps_status_values')),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_job_steps_ordinal_positive')),
    sa.ForeignKeyConstraint(['job_item_id'], ['job_items.id'], name=op.f('fk_job_steps_job_item_id_job_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_steps')),
    sa.UniqueConstraint('job_item_id', 'ordinal', name=op.f('uq_job_steps_job_item_id'))
    )
    op.create_table('operation_artifacts',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_operation_artifacts_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_artifacts_operation_id_operations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_operation_artifacts_page_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('operation_id', 'kind', name=op.f('pk_operation_artifacts'))
    )
    op.create_table('operation_asset_inputs',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_operation_asset_inputs_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_asset_inputs_operation_id_operations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operation_id', 'role', name=op.f('pk_operation_asset_inputs'))
    )
    op.create_table('operation_credential_snapshots',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('credential_version_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['credential_version_id'], ['credential_versions.id'], name=op.f('fk_operation_credential_snapshots_credential_version_id_credential_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_credential_snapshots_operation_id_operations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operation_id', 'credential_version_id', 'role', name=op.f('pk_operation_credential_snapshots'))
    )
    op.create_table('operation_font_snapshots',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('font_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['font_id'], ['fonts.id'], name=op.f('fk_operation_font_snapshots_font_id_fonts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_font_snapshots_operation_id_operations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operation_id', 'font_id', 'role', name=op.f('pk_operation_font_snapshots'))
    )
    op.create_table('operation_plugin_snapshots',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('plugin_version_id', sa.String(length=36), nullable=False),
    sa.Column('config_json', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_plugin_snapshots_operation_id_operations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plugin_version_id'], ['plugin_versions.id'], name=op.f('fk_operation_plugin_snapshots_plugin_version_id_plugin_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('operation_id', 'plugin_version_id', name=op.f('pk_operation_plugin_snapshots'))
    )
    op.create_table('job_drain_acks',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=64), nullable=False),
    sa.Column('worker_slot', sa.Integer(), nullable=False),
    sa.Column('last_step_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('worker_slot >= 0', name=op.f('ck_job_drain_acks_worker_slot_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_drain_acks_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_step_id'], ['job_steps.id'], name=op.f('fk_job_drain_acks_last_step_id_job_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id', 'attempt_id', 'pool_id', 'worker_slot', name=op.f('pk_job_drain_acks'))
    )
    op.create_table('job_step_asset_outputs',
    sa.Column('job_step_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_job_step_asset_outputs_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_step_id'], ['job_steps.id'], name=op.f('fk_job_step_asset_outputs_job_step_id_job_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_step_id', 'role', name=op.f('pk_job_step_asset_outputs'))
    )
    op.create_table('page_assets',
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('input_source_revision', sa.Integer(), nullable=True),
    sa.Column('input_document_revision', sa.Integer(), nullable=True),
    sa.Column('parent_asset_id', sa.String(length=36), nullable=True),
    sa.Column('producer_job_step_id', sa.String(length=36), nullable=True),
    sa.Column('producer_operation_id', sa.String(length=36), nullable=True),
    sa.Column('producer_render_request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(role IN ('thumbnail_source','thumbnail_translated') AND parent_asset_id IS NOT NULL) OR (role NOT IN ('thumbnail_source','thumbnail_translated'))", name=op.f('ck_page_assets_thumbnail_parent_required')),
    sa.CheckConstraint("role IN ('source', 'thumbnail_source', 'clean', 'translated', 'thumbnail_translated', 'text_mask')", name=op.f('ck_page_assets_role_values')),
    sa.CheckConstraint('(CASE WHEN producer_job_step_id IS NULL THEN 0 ELSE 1 END + CASE WHEN producer_operation_id IS NULL THEN 0 ELSE 1 END + CASE WHEN producer_render_request_id IS NULL THEN 0 ELSE 1 END) <= 1', name=op.f('ck_page_assets_single_producer')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_page_assets_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_page_assets_page_id_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], name=op.f('fk_page_assets_parent_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producer_job_step_id'], ['job_steps.id'], name=op.f('fk_page_assets_producer_job_step_id_job_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producer_operation_id'], ['operations.id'], name=op.f('fk_page_assets_producer_operation_id_operations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producer_render_request_id'], ['render_requests.id'], name=op.f('fk_page_assets_producer_render_request_id_render_requests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('page_id', 'role', name=op.f('pk_page_assets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_assets')
    op.drop_table('job_step_asset_outputs')
    op.drop_table('job_drain_acks')
    op.drop_table('operation_plugin_snapshots')
    op.drop_table('operation_font_snapshots')
    op.drop_table('operation_credential_snapshots')
    op.drop_table('operation_asset_inputs')
    op.drop_table('operation_artifacts')
    op.drop_table('job_steps')
    op.drop_table('job_asset_inputs')
    op.drop_index('uq_operations_one_active_studio_session', table_name='operations', sqlite_where=sa.text("studio_session_id IS NOT NULL AND status IN ('pending', 'running') AND kind IN ('studio_chat', 'studio_summary')"))
    op.drop_index('uq_operations_one_active_studio_generate', table_name='operations', sqlite_where=sa.text("studio_document_id IS NOT NULL AND status IN ('pending', 'running') AND kind = 'studio_generate'"))
    op.drop_index('uq_operations_one_active_page_write', table_name='operations', sqlite_where=sa.text("page_id IS NOT NULL AND status IN ('pending', 'running') AND kind IN ('bubble_ocr', 'bubble_color', 'page_detect', 'page_repair', 'bubble_translate')"))
    op.drop_index('ix_operations_executor_claim', table_name='operations')
    op.drop_table('operations')
    op.drop_table('job_plugin_snapshots')
    op.drop_table('job_items')
    op.drop_table('job_font_snapshots')
    op.drop_index('ix_job_events_job_cursor', table_name='job_events')
    op.drop_table('job_events')
    op.drop_table('job_credential_snapshots')
    op.drop_table('job_config_snapshots')
    op.drop_table('job_artifacts')
    op.drop_index('ix_chapter_write_locks_job', table_name='chapter_write_locks')
    op.drop_table('chapter_write_locks')
    op.drop_index('ix_chapter_write_intents_job_set', table_name='chapter_write_intents')
    op.drop_index('ix_chapter_write_intents_epoch_expiry', table_name='chapter_write_intents')
    op.drop_table('chapter_write_intents')
    op.drop_table('web_import_draft_pages')
    op.drop_table('studio_messages')
    op.drop_index('ix_render_requests_claim', table_name='render_requests')
    op.drop_table('render_requests')
    op.drop_index('uq_jobs_one_nonterminal_translation_per_chapter', table_name='jobs', sqlite_where=sa.text("kind = 'translation' AND status IN ('queued', 'running', 'pausing', 'paused', 'cancelling', 'interrupted') AND chapter_id IS NOT NULL"))
    op.execute("DROP INDEX uq_jobs_one_current")
    op.drop_index('ix_jobs_queue_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('chapter_navigation_state')
    op.drop_table('bubbles')
    op.drop_table('web_import_drafts')
    op.drop_table('studio_chat_sessions')
    op.drop_table('pages')
    op.drop_index('ix_import_leases_expires_at', table_name='import_leases')
    op.drop_table('import_leases')
    op.drop_table('translation_constraints')
    op.drop_table('studio_documents')
    op.drop_table('provider_settings')
    op.drop_table('provider_rate_limits')
    op.drop_table('plugin_current_versions')
    op.drop_table('credential_current_versions')
    op.drop_table('chapters')
    op.drop_table('book_tags')
    op.drop_table('book_settings')
    op.drop_table('worker_leases')
    op.drop_table('transient_requests')
    op.drop_table('plugin_versions')
    op.drop_index('uq_fonts_builtin_key', table_name='fonts', sqlite_where=sa.text('builtin_key IS NOT NULL'))
    op.drop_table('fonts')
    op.drop_table('credential_versions')
    op.drop_index('uq_books_one_quick_workspace', table_name='books', sqlite_where=sa.text("kind = 'quick_workspace'"))
    op.drop_table('books')
    op.drop_table('api_executor_leases')
    op.drop_table('tags')
    op.drop_table('queue_state')
    op.drop_table('prompts')
    op.drop_index('ix_process_epochs_role_status', table_name='process_epochs')
    op.drop_table('process_epochs')
    op.drop_table('plugins')
    op.drop_table('object_commit_journal')
    op.drop_table('job_batches')
    op.drop_index('ix_idempotency_records_expires_at', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_table('credentials')
    op.drop_index('ix_assets_gc_marked_at', table_name='assets')
    op.drop_index('ix_assets_checksum', table_name='assets')
    op.drop_table('assets')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
