"""stage5 insight studio plugins

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-29 02:22:41.251255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_message_assets',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_studio_message_assets_ordinal_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_studio_message_assets_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['studio_messages.id'], name=op.f('fk_studio_message_assets_message_id_studio_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'asset_id', name=op.f('pk_studio_message_assets')),
    sa.UniqueConstraint('message_id', 'ordinal', name=op.f('uq_studio_message_assets_message_id'))
    )
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_notes_revision_positive')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_notes_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('ix_notes_book_updated', 'notes', ['book_id', 'updated_at'], unique=False)
    op.create_table('note_citations',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('page_id_snapshot', sa.String(length=36), nullable=False),
    sa.Column('page_number_snapshot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_citations_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_note_citations_page_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('note_id', 'ordinal', name=op.f('pk_note_citations'))
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='staging', nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='2', nullable=False),
    sa.Column('missing_page_ids_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('target_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("scope IN ('full','incremental','chapter','page')", name=op.f('ck_analysis_runs_scope_values')),
    sa.CheckConstraint("status IN ('staging','completed','completed_with_errors','failed','cancelled')", name=op.f('ck_analysis_runs_status_values')),
    sa.CheckConstraint('target_count >= 0 AND success_count >= 0 AND failed_count >= 0', name=op.f('ck_analysis_runs_counts_nonnegative')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_analysis_runs_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_analysis_runs_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs')),
    sa.UniqueConstraint('job_id', name=op.f('uq_analysis_runs_job_id'))
    )
    op.create_index('ix_analysis_runs_book_created', 'analysis_runs', ['book_id', 'created_at'], unique=False)
    op.create_table('analysis_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('template', sa.String(length=64), server_default='default', nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('dependency_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('ready','stale','building','failed','degraded')", name=op.f('ck_analysis_artifacts_status_values')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_analysis_artifacts_revision_positive')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_analysis_artifacts_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_analysis_artifacts_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_artifacts_run_id_analysis_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_artifacts'))
    )
    op.create_index('ix_analysis_artifacts_book_kind_created', 'analysis_artifacts', ['book_id', 'kind', 'created_at'], unique=False)
    op.create_index('uq_analysis_artifacts_active', 'analysis_artifacts', ['book_id', 'kind', 'template'], unique=True, sqlite_where=sa.text('is_active IS 1'))
    op.create_table('analysis_layer_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('layer_index', sa.Integer(), nullable=False),
    sa.Column('layer_name', sa.String(length=200), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('page_range_snapshot_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='staging', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('staging','published','stale')", name=op.f('ck_analysis_layer_results_status_values')),
    sa.CheckConstraint('layer_index >= 0 AND unit_index >= 0', name=op.f('ck_analysis_layer_results_indices_nonnegative')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_analysis_layer_results_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_layer_results_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_layer_results')),
    sa.UniqueConstraint('run_id', 'layer_index', 'unit_index', name=op.f('uq_analysis_layer_results_run_id'))
    )
    op.create_index('ix_analysis_layer_results_run_layer', 'analysis_layer_results', ['run_id', 'layer_index', 'unit_index'], unique=False)
    op.create_table('analysis_page_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('page_id_snapshot', sa.String(length=36), nullable=False),
    sa.Column('page_number_snapshot', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='2', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='staging', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('staging','published','stale')", name=op.f('ck_analysis_page_results_status_values')),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_analysis_page_results_page_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_page_results_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], name=op.f('fk_analysis_page_results_source_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_page_results')),
    sa.UniqueConstraint('run_id', 'page_id_snapshot', name=op.f('uq_analysis_page_results_run_id'))
    )
    op.create_index('ix_analysis_page_results_page_created', 'analysis_page_results', ['page_id', 'created_at'], unique=False)
    op.create_table('analysis_run_targets',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('page_id_snapshot', sa.String(length=36), nullable=False),
    sa.Column('page_number_snapshot', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','completed','failed','conflict')", name=op.f('ck_analysis_run_targets_status_values')),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_analysis_run_targets_ordinal_positive')),
    sa.CheckConstraint('page_number_snapshot >= 1', name=op.f('ck_analysis_run_targets_page_number_positive')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_analysis_run_targets_chapter_id_chapters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_analysis_run_targets_page_id_pages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_run_targets_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], name=op.f('fk_analysis_run_targets_source_asset_id_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'ordinal', name=op.f('pk_analysis_run_targets')),
    sa.UniqueConstraint('run_id', 'page_id_snapshot', name=op.f('uq_analysis_run_targets_run_id'))
    )
    op.create_index('ix_analysis_run_targets_page', 'analysis_run_targets', ['page_id', 'run_id'], unique=False)
    op.create_table('continuation_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_continuation_projects_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_run_id'], ['analysis_runs.id'], name=op.f('fk_continuation_projects_source_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_continuation_projects')),
    sa.UniqueConstraint('book_id', name=op.f('uq_continuation_projects_book_id'))
    )
    op.create_table('timeline_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('dependency_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mode IN ('enhanced','compressed','simple')", name=op.f('ck_timeline_versions_mode_values')),
    sa.CheckConstraint("status IN ('ready','stale','building','failed','degraded')", name=op.f('ck_timeline_versions_status_values')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_timeline_versions_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_timeline_versions_run_id_analysis_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_versions'))
    )
    op.create_index('uq_timeline_versions_active', 'timeline_versions', ['book_id'], unique=True, sqlite_where=sa.text('is_active IS 1'))
    op.create_table('vector_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dependency_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('event_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('ready','stale','building','failed','degraded')", name=op.f('ck_vector_generations_status_values')),
    sa.CheckConstraint('generation >= 1', name=op.f('ck_vector_generations_generation_positive')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_vector_generations_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_vector_generations_run_id_analysis_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vector_generations')),
    sa.UniqueConstraint('book_id', 'generation', name=op.f('uq_vector_generations_book_id'))
    )
    op.create_index('uq_vector_generations_active', 'vector_generations', ['book_id'], unique=True, sqlite_where=sa.text('is_active IS 1'))
    op.create_table('analysis_heads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('active_run_id', sa.String(length=36), nullable=False),
    sa.Column('active_result_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(page_id IS NULL AND active_result_id IS NULL) OR (page_id IS NOT NULL AND active_result_id IS NOT NULL)', name=op.f('ck_analysis_heads_target_shape')),
    sa.ForeignKeyConstraint(['active_result_id'], ['analysis_page_results.id'], name=op.f('fk_analysis_heads_active_result_id_analysis_page_results'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['active_run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_heads_active_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_analysis_heads_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_analysis_heads_page_id_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_heads'))
    )
    op.create_index('uq_analysis_heads_book', 'analysis_heads', ['book_id'], unique=True, sqlite_where=sa.text('page_id IS NULL'))
    op.create_index('uq_analysis_heads_page', 'analysis_heads', ['page_id'], unique=True, sqlite_where=sa.text('page_id IS NOT NULL'))
    op.create_table('analysis_layer_result_pages',
    sa.Column('layer_result_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('page_id_snapshot', sa.String(length=36), nullable=False),
    sa.Column('page_number_snapshot', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordinal >= 1', name=op.f('ck_analysis_layer_result_pages_ordinal_positive')),
    sa.ForeignKeyConstraint(['layer_result_id'], ['analysis_layer_results.id'], name=op.f('fk_analysis_layer_result_pages_layer_result_id_analysis_layer_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('fk_analysis_layer_result_pages_page_id_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('layer_result_id', 'ordinal', name=op.f('pk_analysis_layer_result_pages'))
    )
    op.create_table('continuation_characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('aliases_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['continuation_projects.id'], name=op.f('fk_continuation_characters_project_id_continuation_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_continuation_characters')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_continuation_characters_project_id'))
    )
    op.create_table('continuation_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['continuation_projects.id'], name=op.f('fk_continuation_pages_project_id_continuation_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_continuation_pages')),
    sa.UniqueConstraint('project_id', 'ordinal', name=op.f('uq_continuation_pages_project_id'))
    )
    op.create_table('continuation_scripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['continuation_projects.id'], name=op.f('fk_continuation_scripts_project_id_continuation_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_continuation_scripts'))
    )
    op.create_table('timeline_characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeline_version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_version_id'], ['timeline_versions.id'], name=op.f('fk_timeline_characters_timeline_version_id_timeline_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_characters')),
    sa.UniqueConstraint('timeline_version_id', 'name', name=op.f('uq_timeline_characters_timeline_version_id'))
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeline_version_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_version_id'], ['timeline_versions.id'], name=op.f('fk_timeline_events_timeline_version_id_timeline_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events')),
    sa.UniqueConstraint('timeline_version_id', 'ordinal', name=op.f('uq_timeline_events_timeline_version_id'))
    )
    op.create_index('ix_timeline_events_version_ordinal', 'timeline_events', ['timeline_version_id', 'ordinal'], unique=False)
    op.create_table('continuation_character_forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('reference_asset_id', sa.String(length=36), nullable=True),
    sa.Column('adopted_asset_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['adopted_asset_id'], ['assets.id'], name=op.f('fk_continuation_character_forms_adopted_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['continuation_characters.id'], name=op.f('fk_continuation_character_forms_character_id_continuation_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_asset_id'], ['assets.id'], name=op.f('fk_continuation_character_forms_reference_asset_id_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_continuation_character_forms')),
    sa.UniqueConstraint('character_id', 'name', name=op.f('uq_continuation_character_forms_character_id'))
    )
    op.create_table('continuation_image_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('continuation_page_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_continuation_image_versions_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['continuation_page_id'], ['continuation_pages.id'], name=op.f('fk_continuation_image_versions_continuation_page_id_continuation_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_continuation_image_versions')),
    sa.UniqueConstraint('continuation_page_id', 'version', name=op.f('uq_continuation_image_versions_continuation_page_id'))
    )
    op.add_column('plugin_versions', sa.Column('config_schema_json', sa.Text(), server_default='{}', nullable=False))
    op.add_column('plugins', sa.Column('author', sa.String(length=200), server_default='', nullable=False))
    op.add_column('plugins', sa.Column('description', sa.Text(), server_default='', nullable=False))
    op.add_column('plugins', sa.Column('default_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('plugins', sa.Column('runtime_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('plugins', sa.Column('config_json', sa.Text(), server_default='{}', nullable=False))
    op.add_column('plugins', sa.Column('config_revision', sa.Integer(), server_default='1', nullable=False))
    op.add_column('plugins', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('studio_chat_sessions', sa.Column('variables_json', sa.Text(), server_default='{}', nullable=False))
    op.add_column('studio_chat_sessions', sa.Column('summary_blocks_json', sa.Text(), server_default='[]', nullable=False))
    op.execute(
        sa.text(
            "ALTER TABLE studio_chat_sessions "
            "ADD COLUMN summary_through_message_id VARCHAR(36) "
            "REFERENCES studio_messages(id) ON DELETE SET NULL"
        )
    )
    op.add_column('studio_chat_sessions', sa.Column('summary_generation', sa.Integer(), server_default='0', nullable=False))
    op.add_column('studio_chat_sessions', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_studio_chat_sessions_document_updated', 'studio_chat_sessions', ['document_id', 'updated_at'], unique=False)
    op.create_index('uq_studio_chat_sessions_one_active', 'studio_chat_sessions', ['document_id'], unique=True, sqlite_where=sa.text('archived_at IS NULL'))
    op.execute(
        sa.text(
            "ALTER TABLE studio_documents "
            "ADD COLUMN avatar_asset_id VARCHAR(36) "
            "REFERENCES assets(id) ON DELETE SET NULL"
        )
    )
    op.add_column('studio_messages', sa.Column('runtime_log', sa.Text(), server_default='', nullable=False))
    op.add_column('studio_messages', sa.Column('variables_snapshot_json', sa.Text(), server_default='{}', nullable=False))
    op.add_column('studio_messages', sa.Column('generation_meta_json', sa.Text(), server_default='{}', nullable=False))
    op.add_column('studio_messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index('ix_studio_messages_session_ordinal', 'studio_messages', ['session_id', 'ordinal'], unique=False)
    op.execute(
        sa.text(
            "UPDATE plugins "
            "SET default_enabled = CASE WHEN state = 'enabled' THEN 1 ELSE 0 END, "
            "runtime_enabled = CASE WHEN state = 'enabled' THEN 1 ELSE 0 END"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_studio_messages_session_ordinal', table_name='studio_messages')
    op.drop_column('studio_messages', 'updated_at')
    op.drop_column('studio_messages', 'generation_meta_json')
    op.drop_column('studio_messages', 'variables_snapshot_json')
    op.drop_column('studio_messages', 'runtime_log')
    op.drop_column('studio_documents', 'avatar_asset_id')
    op.drop_index('uq_studio_chat_sessions_one_active', table_name='studio_chat_sessions', sqlite_where=sa.text('archived_at IS NULL'))
    op.drop_index('ix_studio_chat_sessions_document_updated', table_name='studio_chat_sessions')
    op.drop_column('studio_chat_sessions', 'archived_at')
    op.drop_column('studio_chat_sessions', 'summary_generation')
    op.drop_column('studio_chat_sessions', 'summary_through_message_id')
    op.drop_column('studio_chat_sessions', 'summary_blocks_json')
    op.drop_column('studio_chat_sessions', 'variables_json')
    op.drop_column('plugins', 'error_message')
    op.drop_column('plugins', 'config_revision')
    op.drop_column('plugins', 'config_json')
    op.drop_column('plugins', 'runtime_enabled')
    op.drop_column('plugins', 'default_enabled')
    op.drop_column('plugins', 'description')
    op.drop_column('plugins', 'author')
    op.drop_column('plugin_versions', 'config_schema_json')
    op.drop_table('continuation_image_versions')
    op.drop_table('continuation_character_forms')
    op.drop_index('ix_timeline_events_version_ordinal', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_table('timeline_characters')
    op.drop_table('continuation_scripts')
    op.drop_table('continuation_pages')
    op.drop_table('continuation_characters')
    op.drop_table('analysis_layer_result_pages')
    op.drop_index('uq_analysis_heads_page', table_name='analysis_heads', sqlite_where=sa.text('page_id IS NOT NULL'))
    op.drop_index('uq_analysis_heads_book', table_name='analysis_heads', sqlite_where=sa.text('page_id IS NULL'))
    op.drop_table('analysis_heads')
    op.drop_index('uq_vector_generations_active', table_name='vector_generations', sqlite_where=sa.text('is_active IS 1'))
    op.drop_table('vector_generations')
    op.drop_index('uq_timeline_versions_active', table_name='timeline_versions', sqlite_where=sa.text('is_active IS 1'))
    op.drop_table('timeline_versions')
    op.drop_table('continuation_projects')
    op.drop_index('ix_analysis_run_targets_page', table_name='analysis_run_targets')
    op.drop_table('analysis_run_targets')
    op.drop_index('ix_analysis_page_results_page_created', table_name='analysis_page_results')
    op.drop_table('analysis_page_results')
    op.drop_index('ix_analysis_layer_results_run_layer', table_name='analysis_layer_results')
    op.drop_table('analysis_layer_results')
    op.drop_index('uq_analysis_artifacts_active', table_name='analysis_artifacts', sqlite_where=sa.text('is_active IS 1'))
    op.drop_index('ix_analysis_artifacts_book_kind_created', table_name='analysis_artifacts')
    op.drop_table('analysis_artifacts')
    op.drop_index('ix_analysis_runs_book_created', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('note_citations')
    op.drop_index('ix_notes_book_updated', table_name='notes')
    op.drop_table('notes')
    op.drop_table('studio_message_assets')
    # ### end Alembic commands ###
